name: fixnmatch
description: "E-Waste Management App with repair guides, marketplace, and recycling tools."
# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8
  
  # For picking images from gallery or camera
  image_picker: ^1.1.2
  
  # For maps and location services
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  
  # For backend integration
  http: ^1.1.0
  dio: ^5.3.3
  
  # For local storage and caching
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # For state management
  provider: ^6.1.1
  
  # For URL handling
  url_launcher: ^6.2.1
  
  # For Supabase integration
  supabase_flutter: ^2.0.0
  google_sign_in: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints (code quality rules)
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/signin-assets/signin-assets/Web (mobile + desktop)/png@1x/light/web_light_sq_SI@1x.png
    - assets/logo.png

  # Example if you add more images later:
  # assets:
  #   - assets/logo.png
  #   - assets/images/
